apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: httpd-s2i-app-buildconfig
  labels:
    name: httpd-s2i-app-buildconfig
  namespace: html-test
  annotations:
    template.alpha.openshift.io/wait-for-ready: 'true'
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/cellist01/html-test.git'
    type: Git
  strategy:
    type: Custom
    customStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: httpd-s2i-image:latest
        namespace: openshift
      env: []
  output:
    to:
      kind: ImageStreamTag
      name: httpd-image:latest
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange