kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "jboss-s2i-build"
spec:
  runPolicy: "Serial"
  triggers: 
    -
      type: "ImageChange"
  source: 
    git:
      uri: "https://github.com/cellist01/openshift-test.git"
    contextDir: "mavenbuild-test"
  strategy: 
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "custom-jboss-image:1.0"
        namespace: openshift
  output: 
    to:
      kind: "ImageStreamTag"
      name: "custom-jboss-s2i-image:1.0"
      namespace: source-test



